// This file is generated by scripts/sync-version.mjs. Do not edit it manually.
export const APP_NAME = 'TuxPlayerX';
<<<<<<< HEAD
export const APP_VERSION = '2.0.3';
=======
export const APP_VERSION = '2.0.1';
>>>>>>> 4a6b9a44dd637168632007849f9929d8fdae9683
