import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const packagePath = path.join(root, 'package.json');
const cargoPath = path.join(root, 'src-tauri', 'Cargo.toml');
const tauriConfigPath = path.join(root, 'src-tauri', 'tauri.conf.json');
const appMetaPath = path.join(root, 'src', 'lib', 'appMeta.ts');

function fail(message) {
  console.error(`[sync-version] ${message}`);
  process.exit(1);
}

if (!fs.existsSync(packagePath)) fail('package.json was not found. Run this script from the project root.');
if (!fs.existsSync(cargoPath)) fail('src-tauri/Cargo.toml was not found.');
if (!fs.existsSync(tauriConfigPath)) fail('src-tauri/tauri.conf.json was not found.');

const pkg = JSON.parse(fs.readFileSync(packagePath, 'utf8'));
const version = String(pkg.version || '').trim();
const productName = 'TuxPlayerX';

if (!/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(version)) {
  fail(`Invalid package.json version: "${version}". Use semantic versioning, for example 2.0.7.`);
}

let cargo = fs.readFileSync(cargoPath, 'utf8');
cargo = cargo.replace(/^version\s*=\s*"[^"]+"/m, `version = "${version}"`);
fs.writeFileSync(cargoPath, cargo);

const tauriConfig = JSON.parse(fs.readFileSync(tauriConfigPath, 'utf8'));
tauriConfig.productName = productName;
tauriConfig.version = version;
if (tauriConfig.bundle) {
  tauriConfig.bundle.targets = ['deb', 'rpm'];
  tauriConfig.bundle.category = 'Video';
}
fs.writeFileSync(tauriConfigPath, `${JSON.stringify(tauriConfig, null, 2)}\n`);

fs.writeFileSync(
  appMetaPath,
  `// This file is generated by scripts/sync-version.mjs. Do not edit it manually.\n` +
    `export const APP_NAME = '${productName}';\n` +
    `export const APP_VERSION = '${version}';\n`,
);

console.log(`[sync-version] ${productName} version synchronized to ${version}`);
